language: objective-c

osx_image: xcode7.3

before_install:
    - gem install activesupport -v "4.2.6"
    - gem install cocoapods -v "0.39.0"
    - gem install xcpretty

script: 
    - pod install --project-directory=Example
    - xcodebuild -workspace Example/GQModularize.xcworkspace -scheme GQModularize-Example -sdk iphonesimulator test | xcpretty && exit ${PIPESTATUS[0]}
