language: objective-c

before_install:
    - gem install activesupport -v "4.2.6"
    - gem install cocoapods -v "0.39.0"

script: 
    - pod install --project-directory=Example
    - xctool -workspace Example/GQModularize.xcworkspace -scheme GQModularize-Example -sdk iphonesimulator test
